### ISSUE TITLE
Search example text is too bright

### ISSUE THREAD

**Issue by user202729** [GaurangTandon/codeforces-darktheme#27]
![a](https://user-images.githubusercontent.com/25191436/80294359-ca771c00-8792-11ea-92ea-58d8c7e8076b.png)

URL: http://codeforces.com/search?query=query

CSS used by Codeforces:

```
.search-help code {
    font-family: Consolas, "Lucida Console", "Andale Mono", "Bitstream Vera Sans Mono", "Courier New", Courier;
    border: 1px solid #d4d4d4;
    background: #f4f4f4;
    padding: 1px;
}
```

**Comment by GaurangTandon** [comment]
Thanks for this! I fixed it by including a search page specific override in the CSS.
