### ISSUE TITLE
Missing special highlight for completely solved contests on /contests

### ISSUE THREAD

**Issue by user202729** [GaurangTandon/codeforces-darktheme#28]
Related: #7

Contests with all problems solved have a green highlight on /contests page in the normal color scheme.

CSS for partially-solved contest: (currently highlighted gray)

```
.datatable td.state[style^="background-color: rgb(221, 238, 255);"]
```

CSS for completely-solved contest:
```
.datatable td.state[style^="background-color: rgb(212, 237, 201);"] 
```

Currently #b5fd95 is used for solved problem on /contest/ID pages. However it's too bright for the "solved: x out of y" text.

**Comment by GaurangTandon** [comment]
Thanks for this! I have changed it to a dark green kinda color. It doesn't look too great, but I cannot find any other viable option that preserves text readability.
