### ISSUE TITLE
<ins> tag color in code compare window is too bright

### ISSUE THREAD

**Issue by user202729** [GaurangTandon/codeforces-darktheme#29]
```
<ins style="background:#80ff80;overflow-wrap:break-word;"
<del style="background:#ff8080;overflow-wrap:break-word;"
```

White/yellow text are unreadable on light green colors.

Possible CSS selector:

```
div.diffHtmlTarget pre.prettyprint ins[style^="background:#80ff80"] {
    background: #?????? !important;
}

div.diffHtmlTarget pre.prettyprint del[style^="background:#ff8080"] {
    background: #?????? !important;
}

```

**Comment by GaurangTandon** [comment]
Thanks for the report! :) I have changed it to this now, I agree previously it was too bright.

![image](https://user-images.githubusercontent.com/6308683/81489888-a76f6080-9298-11ea-8b8c-c07946227e27.png)

I have manually checked all individual tokens satisfy at least AA readability constraints.

New colors:

1. Deletion: `#7b1313`
2. Insertion: `#004600`
3. Red tokens inside insertion area: `#ff9d9d`
