### ISSUE TITLE
Not showing some tutorial pages, Please fix

### ISSUE THREAD

**Issue by Rohanfizz** [GaurangTandon/codeforces-darktheme#36]
Please check the example page, its not showing the whole tutorial page at all.
Example page - https://codeforces.com/blog/entry/3693

Regards

**Comment by GaurangTandon** [comment]
Hi this is an old tutorial blog and this problem rarely happens. If you can submit a PR, I'll merge it. Thank you.

**Comment by Rohanfizz** [comment]
Okay!
