### ISSUE TITLE
Change the codeforces logo at top at a .PNG

### ISSUE THREAD

**Issue by xSaheel** [GaurangTandon/codeforces-darktheme#37]
![cf](https://user-images.githubusercontent.com/56691452/107007223-3a9dde00-67b8-11eb-905d-ec671857a17d.png)

**Comment by GaurangTandon** [comment]
Thank you for your contribution, however there's a few points that I'd like to mention. If we make it a PNG with full transparent background, the dark "CODE" would look out of place as it would blend in with background. A curvy shape fill - as it is in your provided PNG - will look more distracting than a simple rectangular white fill. So, I would rather skip this logo change.

PS: Please see earlier discussions #24 and #30 to view my perspectives on changing the logo.
