### ISSUE TITLE
Unable to see test cases clearly

### ISSUE THREAD

**Issue by Shubh-Mishra007** [GaurangTandon/codeforces-darktheme#46]
![Screenshot 2022-08-27 at 5 31 44 PM](https://user-images.githubusercontent.com/85950224/187029290-4659848d-52af-417d-a436-29be4a1ea3a2.png)

**Comment by GaurangTandon** [comment]
Hey @Shubh-Mishra007 thanks for letting me know.
If you or someone else can help me out with a PR to fix this issue, that would be great. Otherwise I may try to solve this later but not sure when.

**Comment by GhiathAjam** [comment]
here is a hack that works for now

Add these two functions to usercript file:

```
    (function fixTextInEvenTestCasesInput() {
		applyFuncWhenElmLoaded(".test-example-line.test-example-line-even", function (elm) {
            console.log('gi')
			if ((elm.style && elm.style.color == "rgb(0, 0, 0)" ) || true)
				overrideStyleAttribute(elm, "color", "#212121");
		});
	})();
    (function fixTextInOddTestCasesInput() {
		applyFuncWhenElmLoaded(".test-example-line.test-example-line-odd", function (elm) {
            console.log('goo')
			if ((elm.style && elm.style.color == "rgb(0, 0, 0)" ) || true)
				overrideStyleAttribute(elm, "color", colors.redColorJustPassesA11Y);
		});
	})();
```

**Comment by GaurangTandon** [comment]
Hey @GhiathAjam , appreciate your contribution! And thanks @Shubh-Mishra007 for reporting the issue.

Can you guys please re-install the userscript (so remove and then install) and check out the updated style? :-)  Let me know if it's fine then I'll do a global rollout for all users.

![image](https://user-images.githubusercontent.com/6308683/187232445-be5db49f-731f-4fd2-ae25-edeba0125b41.png)

Unfortunately I was inactive on CF so I noticed a bunch of user comments only now (https://codeforces.com/blog/entry/105858, https://codeforces.com/blog/entry/65477, https://codeforces.com/blog/entry/105779#comment-941360). I'll reply to everyone once this fix is confirmed okay by one of you.

Thanks again!

**Comment by GhiathAjam** [comment]
@GaurangTandon Just Tried, It is Perfect!

**Comment by GaurangTandon** [comment]
Thanks @GhiathAjam for the helpful response :-)

**Comment by fortunate-man** [comment]
Hi, the issue is still occurring for me on Firefox 92.0. Could you try reproducing it on firefox?

![image](https://user-images.githubusercontent.com/12422882/188675865-a1a1bbf6-c668-4791-83cf-af16af6e6b1f.png)

**Comment by GaurangTandon** [comment]
@fortunate-man I have already tested it on Firefox 100+. Do you have any conflicting extensions? Can you double check the userscript version is `1.1.0`?

**Comment by fortunate-man** [comment]
I updated to firefox 104.0.1 and it works now, thanks.
