### ISSUE TITLE
Cannot Install !

### ISSUE THREAD

**Issue by parin23** [GaurangTandon/codeforces-darktheme#47]
Error Loading Resources.
[https://raw.githubusercontent.com/ajaxorg/ace/master/lib/ace/theme/monokai.css]

404 Not found on the Resource Mentioned on line 11

Please Fix Quickly

@GaurangTandon

**Comment by GaurangTandon** [comment]
@parin23 Please try again and let me know if it's fixed now.

**Comment by parin23** [comment]
Fixed, Thanks
