### ISSUE TITLE
New Version of test cases is Unreadable . 

### ISSUE THREAD

**Issue by mtheggi** [GaurangTandon/codeforces-darktheme#49]
the new test case (input table ) is white and black. In the white section, numbers and letters are not readable. Attached below a screenshot. 
![issue](https://user-images.githubusercontent.com/88272272/196008378-b454dcd6-f276-4660-bc9c-4bf8aab6cce6.JPG)

**Comment by GaurangTandon** [comment]
Thanks @mtheggi for the report. This is fixed now. Let me know if you spot any other bugs any where else.
