### ISSUE TITLE
New codeforces feature that highlights the sample inputs makes it almost impossible to see them with this theme

### ISSUE THREAD

**Issue by viniciusth** [GaurangTandon/codeforces-darktheme#50]
![image](https://user-images.githubusercontent.com/38231257/196044251-9aff3348-8309-4022-8319-1ff123069dfe.png)

**Comment by GaurangTandon** [comment]
@viniciusth Can you please try to install the userscript again? Remove and re-install?

I had fixed the issue yesterday, see: #49

**Comment by viniciusth** [comment]
It worked! Thanks!
