### ISSUE TITLE
Not work in my firefox now, plz help me.

### ISSUE THREAD

**Issue by farukomarmd** [GaurangTandon/codeforces-darktheme#51]
i used this from a more day, but unfortunately uninstall from my firefox. i can"t fix this issue.

**Comment by GaurangTandon** [comment]
HI @csomarfaruk 

As discussed here #52 this is a problem with Tampermonkey add-on itself. 

The temporary workaround is to downgrade your Tampermonkey version on Firefox. You can do that from here: https://addons.mozilla.org/firefox/addon/tampermonkey/versions/

Please let me know if it does not work for you even after downgrading Tampermonkey.
