### ISSUE TITLE
its is not working anymore

### ISSUE THREAD

**Issue by siddhanttomar2003** [GaurangTandon/codeforces-darktheme#53]

**Comment by GaurangTandon** [comment]
Hi @siddhanttomar2003 as suggested here please try Tampermonkey Beta

https://github.com/GaurangTandon/codeforces-darktheme/issues/52#issuecomment-2438508650

I'm closing this issue in the meanwhile. If you notice it's not working even with Tampermonkey Beta, please do let me know.
