### ISSUE TITLE
The script doesn't work anymore?

### ISSUE THREAD

**Issue by Dangcaominh** [GaurangTandon/codeforces-darktheme#55]
Is this my own local problem or because of Tampermonkey update? I have installed this script properly with the lastest Tampermonkey extension, but recently (formerly working) when I enter codeforces, it goes black for a short period of time and suddenly goes all white.

https://github.com/user-attachments/assets/23edf55d-db44-4708-bd98-33ecc8c00bd8

**Comment by GaurangTandon** [comment]
Hi @Dangcaominh  can you please try the suggestion here and let me know if it works for you?

https://github.com/GaurangTandon/codeforces-darktheme/issues/52#issuecomment-2438508650

**Comment by Dangcaominh** [comment]
Thanks, it works again.
